name: BHUGA WOOGA
gems: [jekyll-coffeescript]
markdown: kramdown
permalink: :title
sass:
  sass_dir: assets/stylesheets
collections:
  book_reviews:
    output: true
    permalink: :title
exclude:
  - config.ru
  - book_reviews
  - blog_posts
  - Gemfile
  - Gemfile.lock
  - lib
  - bin
  - .gitignore
  - .bundle
  - .ruby-version
  - views
  - vendor
