name: BHUGA WOOGA
gems: [jekyll-coffeescript]
markdown: kramdown
permalink: :title
sass:
  sass_dir: assets/stylesheets
collections:
  book_reviews:
    output: true
    permalink: :title
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - .gitignore
  - .bundle
  - .ruby-version
  - vendor
